# ce fichier permet d'afficher les routes (URL) de mon site


# page accueil
index: # je choisis le nom unique de ma route /!\ pas de doublons /!\
    path: / # Ma route
    controller: App\Controller\DefaultController::index # le controller s'execute quand la route est détéctée

#page contact
contact: # je choisis le nom unique de ma route /!\ pas de doublons /!\
    path: /page/contact
    controller: App\Controller\DefaultController::contact